import type {
  AoiSeedData,
  AoiSystemSchema
} from "@aoi/protocol"

export const adminCrudProjectId = "admin_crud"

export const adminCrudSystemSchema: AoiSystemSchema = {
  app: {
    description: "A schema-first CRUD admin system generated by Aoi Builder.",
    name: "Admin CRUD Console",
    slug: "admin-crud-console"
  },
  build: {
    defaultLocale: "zh-CN",
    target: "nuxt"
  },
  dataSources: [
    {
      driver: "sqlite-node",
      id: "localSqlite",
      label: "Local SQLite",
      models: [
        {
          displayField: "name",
          fields: [
            { id: "id", label: "ID", required: true, type: "string" },
            { id: "name", label: "Customer", required: true, type: "string" },
            { id: "segment", label: "Segment", type: "enum", enumOptions: ["Enterprise", "SMB", "Startup"] },
            { id: "owner", label: "Owner", type: "string" },
            { id: "status", label: "Status", type: "enum", enumOptions: ["active", "paused", "risk"] },
            { id: "createdAt", label: "Created At", type: "datetime" }
          ],
          id: "customers",
          label: "Customer",
          pluralLabel: "Customers"
        },
        {
          displayField: "title",
          fields: [
            { id: "id", label: "ID", required: true, type: "string" },
            { id: "title", label: "Order", required: true, type: "string" },
            { id: "customerName", label: "Customer", type: "string" },
            { id: "amount", label: "Amount", type: "number" },
            { id: "status", label: "Status", type: "enum", enumOptions: ["draft", "confirmed", "shipped", "closed"] },
            { id: "createdAt", label: "Created At", type: "datetime" }
          ],
          id: "orders",
          label: "Order",
          pluralLabel: "Orders"
        },
        {
          displayField: "title",
          fields: [
            { id: "id", label: "ID", required: true, type: "string" },
            { id: "title", label: "Task", required: true, type: "string" },
            { id: "requester", label: "Requester", type: "string" },
            { id: "assignee", label: "Assignee", type: "string" },
            { id: "priority", label: "Priority", type: "enum", enumOptions: ["low", "normal", "high"] },
            { id: "status", label: "Status", type: "enum", enumOptions: ["pending", "approved", "rejected"] },
            { id: "createdAt", label: "Created At", type: "datetime" }
          ],
          id: "approvalTasks",
          label: "Approval Task",
          pluralLabel: "Approval Tasks"
        }
      ],
      resources: [
        { driver: "sqlite-node", id: "customersResource", label: "Customers", modelId: "customers", operations: ["query", "create", "update", "delete", "seed", "reset"] },
        { driver: "sqlite-node", id: "ordersResource", label: "Orders", modelId: "orders", operations: ["query", "create", "update", "delete", "seed", "reset"] },
        { driver: "sqlite-node", id: "approvalTasksResource", label: "Approval Tasks", modelId: "approvalTasks", operations: ["query", "create", "update", "delete", "seed", "reset"] }
      ]
    }
  ],
  id: adminCrudProjectId,
  materials: [
    { type: "aoi.layout.container", version: "0.1.0" },
    { type: "aoi.display.text", version: "0.1.0" },
    { type: "aoi.action.button", version: "0.1.0" },
    { type: "aoi.data.table", version: "0.1.0" },
    { type: "aoi.form.model", version: "0.1.0" },
    { type: "aoi.feedback.status", version: "0.1.0" },
    { type: "aoi.composite.placeholder", version: "0.1.0" }
  ],
  modules: [
    {
      description: "Customer, order, and approval task operations for a generic admin console.",
      id: "operations",
      modelIds: ["customers", "orders", "approvalTasks"],
      name: "Operations",
      pageIds: ["dashboard", "customersPage", "ordersPage", "approvalsPage"]
    }
  ],
  pages: [
    {
      description: "Overview page with navigation actions and operational status.",
      id: "dashboard",
      name: "Dashboard",
      routePath: "/",
      state: {},
      root: {
        children: [
          {
            id: "dashboardTitle",
            material: "aoi.display.text",
            props: { text: "Admin CRUD Console", variant: "title" }
          },
          {
            id: "dashboardIntro",
            material: "aoi.display.text",
            props: { text: "A clean generated runtime driven by Schema, local SQLite, and reusable materials.", variant: "body" }
          },
          {
            id: "dashboardStatus",
            material: "aoi.feedback.status",
            props: { message: "SQLite is the V1 data bus. The builder never submits arbitrary SQL.", tone: "success" }
          },
          {
            id: "dashboardActions",
            material: "aoi.layout.container",
            props: { as: "div", surface: "plain", title: "Primary flows" },
            children: [
              {
                events: { click: { steps: [{ kind: "navigate", to: "/customers" }] } },
                id: "openCustomers",
                material: "aoi.action.button",
                props: { label: "Open Customers", tone: "primary" }
              },
              {
                events: { click: { steps: [{ kind: "navigate", to: "/orders" }] } },
                id: "openOrders",
                material: "aoi.action.button",
                props: { label: "Open Orders", tone: "neutral" }
              },
              {
                events: { click: { steps: [{ kind: "navigate", to: "/approvals" }] } },
                id: "openApprovals",
                material: "aoi.action.button",
                props: { label: "Open Approvals", tone: "neutral" }
              }
            ]
          }
        ],
        id: "dashboardRoot",
        material: "aoi.layout.container",
        props: { as: "section", surface: "panel", title: "System Overview" }
      }
    },
    {
      description: "Customer list and create form.",
      id: "customersPage",
      name: "Customers",
      routePath: "/customers",
      state: {},
      root: {
        children: [
          { id: "customersTitle", material: "aoi.display.text", props: { text: "Customers", variant: "title" } },
          { id: "customersTable", material: "aoi.data.table", props: { limit: 8, resourceId: "customersResource" } },
          {
            id: "customersForm",
            material: "aoi.form.model",
            props: { modelId: "customers", submitLabel: "Create Customer" },
            events: {
              submit: {
                steps: [
                  { kind: "data.create", resourceId: "customersResource", payloadBindings: [{ source: "event", from: "record" }] },
                  { kind: "toast", message: "Customer action submitted.", tone: "success" }
                ]
              }
            }
          }
        ],
        id: "customersRoot",
        material: "aoi.layout.container",
        props: { as: "section", surface: "panel", title: "Customer Workspace" }
      }
    },
    {
      description: "Order list and create form.",
      id: "ordersPage",
      name: "Orders",
      routePath: "/orders",
      state: {},
      root: {
        children: [
          { id: "ordersTitle", material: "aoi.display.text", props: { text: "Orders", variant: "title" } },
          { id: "ordersTable", material: "aoi.data.table", props: { limit: 8, resourceId: "ordersResource" } },
          {
            id: "ordersForm",
            material: "aoi.form.model",
            props: { modelId: "orders", submitLabel: "Create Order" },
            events: {
              submit: {
                steps: [
                  { kind: "data.create", resourceId: "ordersResource", payloadBindings: [{ source: "event", from: "record" }] },
                  { kind: "toast", message: "Order action submitted.", tone: "success" }
                ]
              }
            }
          }
        ],
        id: "ordersRoot",
        material: "aoi.layout.container",
        props: { as: "section", surface: "panel", title: "Order Workspace" }
      }
    },
    {
      description: "Approval task list and status flow.",
      id: "approvalsPage",
      name: "Approvals",
      routePath: "/approvals",
      state: {},
      root: {
        children: [
          { id: "approvalsTitle", material: "aoi.display.text", props: { text: "Approval Tasks", variant: "title" } },
          { id: "approvalsTable", material: "aoi.data.table", props: { limit: 8, resourceId: "approvalTasksResource" } },
          { id: "approvalsStatus", material: "aoi.feedback.status", props: { message: "Use the data console to approve, reject, or reset task records.", tone: "info" } }
        ],
        id: "approvalsRoot",
        material: "aoi.layout.container",
        props: { as: "section", surface: "panel", title: "Approval Workspace" }
      }
    }
  ],
  routes: [
    { pageId: "dashboard", path: "/", title: "Dashboard" },
    { pageId: "customersPage", path: "/customers", title: "Customers" },
    { pageId: "ordersPage", path: "/orders", title: "Orders" },
    { pageId: "approvalsPage", path: "/approvals", title: "Approvals" }
  ],
  version: "aoi.system.v1"
}

export const adminCrudSeedData: AoiSeedData = {
  approvalTasks: [
    { id: "task_001", assignee: "Mika", createdAt: "2026-06-01T09:00:00.000Z", priority: "high", requester: "Finance", status: "pending", title: "Approve enterprise contract" },
    { id: "task_002", assignee: "Noa", createdAt: "2026-06-02T11:30:00.000Z", priority: "normal", requester: "Sales", status: "approved", title: "Review renewal discount" },
    { id: "task_003", assignee: "Rin", createdAt: "2026-06-03T14:20:00.000Z", priority: "low", requester: "Support", status: "rejected", title: "Archive stale request" }
  ],
  customers: [
    { id: "cust_001", createdAt: "2026-05-20T08:00:00.000Z", name: "Northstar Labs", owner: "Rin", segment: "Enterprise", status: "active" },
    { id: "cust_002", createdAt: "2026-05-22T10:10:00.000Z", name: "Fable Retail", owner: "Mika", segment: "SMB", status: "paused" },
    { id: "cust_003", createdAt: "2026-05-26T16:30:00.000Z", name: "Quartz Studio", owner: "Noa", segment: "Startup", status: "risk" }
  ],
  orders: [
    { id: "ord_001", amount: 12800, createdAt: "2026-06-01T12:00:00.000Z", customerName: "Northstar Labs", status: "confirmed", title: "Platform annual plan" },
    { id: "ord_002", amount: 4200, createdAt: "2026-06-02T12:00:00.000Z", customerName: "Fable Retail", status: "draft", title: "Enablement package" },
    { id: "ord_003", amount: 980, createdAt: "2026-06-03T12:00:00.000Z", customerName: "Quartz Studio", status: "shipped", title: "Prototype workshop" }
  ]
}
